CREATE TABLE IF NOT EXISTS users
(
    user_id  NUMBER GENERATED BY DEFAULT AS IDENTITY,
    login    VARCHAR2(25)  NOT NULL,
    password VARCHAR2(125) NOT NULL,
    email    VARCHAR2(50)  NOT NULL,
    PRIMARY KEY (user_id)
);
INSERT INTO users(login, password, email) VALUES('coolLogin', '1234', 'coolEmail@email.ru');
INSERT INTO users(login, password, email) VALUES('anotherLogin', 'qwerty', 'anotherEmail@email.ru');
INSERT INTO users(login, password, email) VALUES('thirdLogin', 'zxcvb', 'thirdEmail@email.ru');